### ISSUE TITLE
Blacklist error

### ISSUE THREAD

**Issue by Noobi3** [beng-mods/opcodes-4-dummies#1]
[dispatch] handle: error running raw hook for C_PRESS_SKILL<raw>
hook: (anonymous) in alex-logger
data: 170088d2844e000400b6608146af17a444c4378ac53299
error: blacklist is not iterable
    at shouldPrintKnownPacket (C:\Users\Eduftz\Desktop\tera-proxy\bin\node_modules\alex-logger\index.js:190:20)
    at Object.AlexLogger.dispatch.hook [as callback] (C:\Users\Eduftz\Desktop\tera-proxy\bin\node_modules\alex-logger\index.js:265:9)

**Comment by beng-mods** [comment]
fIXED
